{{- if eq .Values.method "A" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" "connect-elector") }}
  labels: { app: connect }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" "connect-elector") }}
  labels: { app: connect }
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" "connect-elector") }}
  labels: { app: connect }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rrcs.name" (dict "root" $ "base" "connect-elector") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rrcs.name" (dict "root" $ "base" "connect-elector") }}
{{- end }}
