route:
  receiver: alert-sink
  group_by: ["alertname","namespace","job","reason"]
  group_wait: 0s
  group_interval: 5s
  repeat_interval: 1m
receivers:
  - name: alert-sink
    webhook_configs:
      - url: http://alert-sink:9099/webhook
        send_resolved: true
