apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-source-config
  labels: { app: connect-source }
data:
  connect.yaml: |-
{{ tpl (.Files.Get (printf "files/connect/%s-forward.yaml" .Values.profile)) . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-sink-config
  labels: { app: connect-sink }
data:
  connect.yaml: |-
{{ tpl (.Files.Get (printf "files/connect/%s-reverse.yaml" .Values.profile)) . | indent 4 }}
