{{- if not .Values.nats.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" .Values.nats.auth.secrets.publisher) }}
  labels: { app: nats-auth, role: publisher }
type: Opaque
data:
  user.creds: {{ .Files.Get "files/nats-auth/publisher.creds" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" .Values.nats.auth.secrets.subscriber) }}
  labels: { app: nats-auth, role: subscriber }
type: Opaque
data:
  user.creds: {{ .Files.Get "files/nats-auth/subscriber.creds" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rrcs.name" (dict "root" $ "base" .Values.nats.auth.secrets.admin) }}
  labels: { app: nats-auth, role: admin }
type: Opaque
data:
  user.creds: {{ .Files.Get "files/nats-auth/admin.creds" | b64enc | quote }}
{{- end }}
