#!/usr/bin/env bash
# Render the chart's forward/reverse Connect pipelines into standalone run-mode
# configs for the lab. Metric blocks are preserved verbatim; only NATS creds are
# stripped (auth-less lab NATS) and connection values come from lab-values.yaml.
#
# NOTE on extraction: the plan's original guess (`.data."cdc-forward.yaml"` /
# `.data."cdc-reverse.yaml"`) does not match what the chart actually emits.
# templates/connect-configmaps.yaml renders THREE separate ConfigMaps, each
# with a single data key ("observability.yaml" or "pipeline.yaml"),
# distinguished by name/labels, not by a per-leg data key:
#   lab-connect-observability      (labels.app=connect,        data: observability.yaml)
#   lab-connect-source-pipeline    (labels.app=connect-source,  data: pipeline.yaml)
#   lab-connect-sink-pipeline      (labels.app=connect-sink,    data: pipeline.yaml)  [default sinkGroup]
#   lab-connect-sink-others-pipeline (labels.app=connect-sink-others, data: pipeline.yaml) [catchAll sinkGroup — not captured]
# So we select ConfigMap documents by `metadata.labels.app`, not by data key.
# The "others" catch-all group's pipeline exists (lab-values.yaml enables it so
# the forward leg's cdc_forward_unrouted/cdc_forward_others switch branches
# actually render — see lab-values.yaml comment) but the lab only wires one
# source + one sink container, so only the "default" sink group's pipeline is
# extracted.
set -euo pipefail

# yq (mikefarah v4) is not on PATH in this environment; locate it robustly.
yq="$(command -v yq || echo "$(go env GOPATH)/bin/yq")"
if ! "$yq" --version >/dev/null 2>&1; then
  echo "FATAL: yq not found/usable (tried PATH and \$(go env GOPATH)/bin/yq)" >&2
  exit 1
fi

here="$(cd "$(dirname "$0")/.." && pwd)"
root="$(cd "$here/../.." && pwd)"           # worktree root
chart="$root/chart"
obs="$chart/files/connect/observability.yaml"
out="$here/connect"; mkdir -p "$out"

render_leg() {  # $1 = leg (forward|reverse)  $2 = ConfigMap app label  $3 = output file  $4 = component label
  local leg="$1" applabel="$2" dst="$3" complabel="$4"
  # Pull the rendered stream body out of the connect-configmaps.yaml ConfigMap
  # whose labels.app matches (see extraction note above).
  local body
  body="$(helm template "$chart" -f "$here/lab-values.yaml" \
            --show-only templates/connect-configmaps.yaml \
          | "$yq" eval-all "select(.kind == \"ConfigMap\" and .metadata.labels.app == \"${applabel}\") | .data.\"pipeline.yaml\"" -)"
  if [ -z "$body" ] || [ "$body" = "null" ]; then
    echo "FATAL: empty render for $leg (app=$applabel) — inspect: helm template $chart -f $here/lab-values.yaml --show-only templates/connect-configmaps.yaml" >&2
    exit 1
  fi
  {
    echo "# GENERATED by scripts/render-configs.sh — DO NOT EDIT. Source: chart cdc-${leg}.yaml"
    echo "# Run-mode assembly: observability.yaml (http/logger/metrics) + the rendered"
    echo "# stream body below. The inherited chart comments still describe streams-mode"
    echo "# (elector POSTs this over the REST API) — here it is loaded directly as a"
    echo "# single run-mode config, so the elector's pod-name placeholder label is"
    echo "# resolved to a fixed label ($complabel)."
    cat "$obs"                                   # http/logger/metrics (run-mode top level)
    echo "$body" \
      | grep -vE '^[[:space:]]*(user_credentials_file:|auth:[[:space:]]*$)' \
      | sed "s/__POD__/${complabel}/g"
  } > "$dst"
  echo "wrote $dst"
}

render_leg forward connect-source "$out/source.yaml" connect_source
render_leg reverse  connect-sink  "$out/sink.yaml"   connect_sink
