input:
  label: redis_source
  redis_streams:
    url: {{ include "rrcs.redis.central.url" . }}
    kind: simple
    streams: [app.events]
    consumer_group: electors
    client_id: __POD__
    body_key: value
    create_streams: true
    start_from_oldest: false
    commit_period: 200ms
    timeout: 500ms
    limit: 50
    auto_replay_nacks: true
pipeline:
  threads: 1
  processors:
    - redis:
        url: {{ include "rrcs.redis.central.url" . }}
        command: incr
        args_mapping: 'root = [ "consumed:__POD__" ]'
output:
  label: drop_sink
  drop: {}
