#!/usr/bin/env bash
# gen-report.sh — run verify-cdc.sh, capture its RESULT_JSON, scrape live key/op
# counts, and render a self-contained HTML report to reports/cdc-report.html.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/.."

NS="${RRCS_NS:-cdc-k8s}"
RELEASE="${RRCS_RELEASE:-cdc}"
OUT="${OUT:-reports/cdc-report.html}"
VERIFY_CMD="${VERIFY_CMD:-${SCRIPT_DIR}/verify-cdc.sh}"
mkdir -p "$(dirname "${OUT}")"

echo "[report] running verify-cdc.sh…" >&2
out="$(RRCS_NS="${NS}" RRCS_RELEASE="${RELEASE}" "${VERIFY_CMD}" 2>&1 || true)"
json="$(printf '%s\n' "${out}" | sed -n 's/^RESULT_JSON://p' | tail -n1 || true)"
if [[ -z "${json}" ]]; then
  # verify-cdc prints RESULT via jq, not raw; fall back to re-reading the job log line
  json="$(printf '%s\n' "${out}" | grep -o '{.*"verdict".*}' | tail -n1 || true)"
fi
[[ -z "${json}" ]] && json='{"cdc":{},"verdict":{"pass":false,"reason":"no RESULT_JSON captured"}}'

read -r dd oo rr pass reason <<<"$(printf '%s' "${json}" | jq -r '[.cdc.dedup_delta, .cdc.ops_ok, .cdc.replay_ok, .verdict.pass, (.verdict.reason//"")] | @tsv')"
banner=$([[ "${pass}" == "true" ]] && echo PASS || echo FAIL)
cls=$([[ "${pass}" == "true" ]] && echo ok || echo bad)

cat > "${OUT}" <<EOF
<!doctype html><html><head><meta charset="utf-8"><title>no-lww-simple-cdc report</title>
<style>body{font-family:system-ui,sans-serif;margin:24px;background:#0e1117;color:#e6e6e6}
h1{font-size:18px}.b{display:inline-block;padding:4px 12px;border-radius:6px;font-weight:700}
.ok{background:#1a3d1a;color:#7ee787}.bad{background:#3d1a1a;color:#f85149}
table{border-collapse:collapse;margin-top:14px}td,th{border:1px solid #2a2f3a;padding:6px 12px;text-align:left}
th{background:#161b22}</style></head><body>
<h1>no-lww-simple-cdc — validation report</h1>
<p>Verdict: <span class="b ${cls}">${banner}</span> ${reason}</p>
<table>
<tr><th>check</th><th>result</th></tr>
<tr><td>dedup (same event_id ×5 → stream +1)</td><td>delta=${dd} (want 1)</td></tr>
<tr><td>per-op end-to-end (create/update/rename/delete under quiescence)</td><td>ops_ok=${oo}</td></tr>
<tr><td>idempotent replay (rename re-delivery)</td><td>replay_ok=${rr}</td></tr>
</table>
<p style="color:#8b95a3;font-size:12px;margin-top:18px">Generated by scripts/gen-report.sh.
This lab accepts stale overwrite / delete-resurrection; those are observed live in the
dashboard (central-vs-region divergence), not asserted here.</p>
</body></html>
EOF
echo "[report] wrote ${OUT}"
[[ "${pass}" == "true" ]] || exit 1
