#!/usr/bin/env bash
# gen-pipelines.sh — Produce the lab's config-file-mode Connect pipelines by
# RENDERING the chart's real forward/reverse pipelines (helm template) and applying
# ONLY the minimal, enumerated diffs (DESIGN §5.2/§5.3, decision D6). Rendering (not
# hand-copying) removes Helm-template translation risk; the diff list is closed so
# the lab stays semantically comparable to the production pipeline.
#
# Outputs (into $LAB/pipelines/):
#   forward.yaml        — source leg, config-file mode (obs http/logger/metrics + input/pipeline/output)
#   reverse.tpl.yaml    — sink leg template with __PORT__ / __PREFIX__ placeholders
#
# Forward diffs vs chart source pipeline:
#   1. mapping: derive meta kv_prefix = first ':' segment of kv_key (fallback new_key; else "unknown")
#   2. output subject: kv.cdc.<op>            -> kv.cdc.<kv_prefix>.<op>
#   3. output label:   __POD__                -> lab_src   (no elector in the lab to substitute it)
# Reverse diffs vs chart sink pipeline:
#   1. input urls:     nats://lab-nats:4222   -> nats://lab-toxiproxy:__PORT__
#   2. input durable:  cdc_sink               -> cdc_sink___PREFIX__   (bind:true kept)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB="$(cd "$HERE/.." && pwd)"
REPO="$(cd "$LAB/../.." && pwd)"
RELEASE="${RELEASE:-cdc}"
# Source-leg throughput knobs (DESIGN §5.2 — tuned only because S0 showed the single
# source pod, not the sink, was the bottleneck at 0-toxic; recorded in the report).
# Defaults raise the rendered values (limit 50 / threads 2 / max_in_flight 256).
SRC_READ_LIMIT="${SRC_READ_LIMIT:-500}"
SRC_THREADS="${SRC_THREADS:-8}"
SRC_MAX_INFLIGHT="${SRC_MAX_INFLIGHT:-2048}"
OUT="$LAB/pipelines"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "[gen-pipelines] rendering chart configmaps (release=$RELEASE)"
helm template "$RELEASE" "$REPO/chart" -f "$REPO/chart/values-dev.yaml" \
  -s templates/connect-configmaps.yaml > "$TMP/cm.yaml"

# extract $2 (data key) block from configmap named $1, de-indenting 4 spaces.
extract() {
  awk -v want="$1" -v key="$2" '
    /^  name: / {cur=$2}
    $0 ~ ("^  " key ": \\|-?$") {if(cur==want){g=1}; next}
    g {if($0 ~ /^---/ || $0 ~ /^[a-zA-Z]/){g=0} else {sub(/^    /,""); print}}
  ' "$TMP/cm.yaml"
}

extract lab-connect-observability   observability.yaml > "$TMP/obs.yaml"
extract lab-connect-source-pipeline  pipeline.yaml      > "$TMP/src.yaml"
extract lab-connect-sink-pipeline    pipeline.yaml      > "$TMP/snk.yaml"

for f in obs src snk; do
  [ -s "$TMP/$f.yaml" ] || { echo "[gen-pipelines] FATAL: empty extraction for $f (chart layout changed?)"; exit 1; }
done

# ---- forward.yaml: obs header + patched source ----
{
  echo "# GENERATED by gen-pipelines.sh from chart forward pipeline + DESIGN §5.2 diffs. Do not hand-edit."
  cat "$TMP/obs.yaml"
  awk '
    # diff 3: output label
    /^  label: __POD__$/ { print "  label: lab_src"; next }
    # diff 2: publish subject -> insert kv_prefix segment
    /^        subject: "kv\.cdc\./ {
      print "        subject: \"kv.cdc.${! meta(\\\"kv_prefix\\\") }.${! meta(\\\"op\\\") }\""
      next
    }
    { print }
    # diff 1: after the last mapping meta line, append kv_prefix derivation
    /^        meta event_id = \$eid/ {
      print "        # LAB DIFF (by-key-prefix-split): route by the first colon segment of the"
      print "        # key. rename events carry an empty kv_key, so fall back to new_key; if both"
      print "        # are empty -> \"unknown\" (subject kv.cdc.unknown.> has no consumer; the"
      print "        # harness asserts that subject count stays 0 — see DESIGN R8)."
      print "        let pfx_src = if meta(\"kv_key\").or(\"\") != \"\" { meta(\"kv_key\") } else { meta(\"new_key\").or(\"\") }"
      print "        meta kv_prefix = if $pfx_src != \"\" { $pfx_src.split(\":\").index(0) } else { \"unknown\" }"
    }
  ' "$TMP/src.yaml"
} > "$OUT/forward.yaml"

# ---- reverse.tpl.yaml: obs header + patched sink (with placeholders) ----
{
  echo "# GENERATED by gen-pipelines.sh from chart reverse pipeline + DESIGN §5.3 diffs. Do not hand-edit."
  echo "# Placeholders: __PORT__ (toxiproxy listener), __PREFIX__ (key prefix). Filled by gen-sink-configs.sh."
  cat "$TMP/obs.yaml"
  awk '
    /^      - "nats:\/\/lab-nats:4222"$/ { print "      - \"nats://lab-toxiproxy:__PORT__\""; next }
    /^    durable: "cdc_sink"$/          { print "    durable: \"cdc_sink___PREFIX__\""; next }
    { print }
  ' "$TMP/snk.yaml"
} > "$OUT/reverse.tpl.yaml"

# Source throughput tuning (only the source forward.yaml; reverse threads untouched).
sed -i \
  -e "s/^    limit: 50$/    limit: ${SRC_READ_LIMIT}/" \
  -e "s/^  threads: 2$/  threads: ${SRC_THREADS}/" \
  -e "s/^        max_in_flight: 256$/        max_in_flight: ${SRC_MAX_INFLIGHT}/" \
  "$OUT/forward.yaml"
echo "[gen-pipelines] source knobs: limit=${SRC_READ_LIMIT} threads=${SRC_THREADS} max_in_flight=${SRC_MAX_INFLIGHT}"

echo "[gen-pipelines] wrote $OUT/forward.yaml ($(wc -l < "$OUT/forward.yaml") lines)"
echo "[gen-pipelines] wrote $OUT/reverse.tpl.yaml ($(wc -l < "$OUT/reverse.tpl.yaml") lines)"

# sanity: the diffs actually landed
grep -q 'meta kv_prefix =' "$OUT/forward.yaml"                || { echo "FATAL: kv_prefix diff missing"; exit 1; }
grep -q 'kv.cdc.${! meta(\\"kv_prefix\\")' "$OUT/forward.yaml" 2>/dev/null || \
  grep -q 'kv_prefix' "$OUT/forward.yaml"                     || { echo "FATAL: subject diff missing"; exit 1; }
grep -q 'label: lab_src' "$OUT/forward.yaml"                  || { echo "FATAL: label diff missing"; exit 1; }
grep -q 'nats://lab-toxiproxy:__PORT__' "$OUT/reverse.tpl.yaml" || { echo "FATAL: toxiproxy url diff missing"; exit 1; }
grep -q 'cdc_sink___PREFIX__' "$OUT/reverse.tpl.yaml"         || { echo "FATAL: durable diff missing"; exit 1; }
echo "[gen-pipelines] all diffs verified present"
